### ISSUE TITLE
'and' keyword not supported by library.

### ISSUE THREAD

**Issue by Abdo-461** [CyberAP/vue-component-media-queries#10]
I am trying to use the 'and' keyword with media query but this library doesn't not support it. It would be nice to have 'and' working with media query in Vue similar to normal media query in Javascript.

**Comment by CyberAP** [comment]
Could you give an example please? It seems to work just fine for me.

**Comment by Abdo-461** [comment]
I am developing using Nuxt Js and in the <style> tag, I am trying to write a media query. A media query with a single parameter works just fine and I am able to view it for that specific screen size, but then, when I want to put 2 parameters and use the 'and' keyword, the media query itself stops working. I know that because when when I am testing on a mobile browser, the styles gets all haywire removing the 'and' part of they query reverts the views back to how it was. 
When I inspect the element, without the 'and' keyword, I could see the specific style for the specific elements, on a specific device screen size. With the 'and' keyword, it just shows the default CSS. 

![Screen Shot 2021-10-27 at 6 59 03 am](https://user-images.githubusercontent.com/55775237/138952728-b1ee2fad-286a-4697-8879-e40bf5a75cfc.png)


Check out the screen shot, whatever before the 'and' works perfectly, when using 'and', none of these parameters, before or after takes effect.

**Comment by CyberAP** [comment]
Can you show how you're using the library please? It doesn't work with CSS in any shape or form, it's for programmatic control (JS) only.

**Comment by Abdo-461** [comment]
The screenshot shows exactly how I use it. In Nuxt Js, there is the <style> tag.
<style>
@media query(....){
  //css here
}
</style>

It works well in the format described.

**Comment by CyberAP** [comment]
This library is unrelated to how you write CSS, you should only use it if you need JS code to know about media queries.

**Comment by Abdo-461** [comment]
Thank you for your reply.
